name: Deploy to GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SECRET_SAMTEK_LANDING }}" > ~/.ssh/id_landing_page
          chmod 600 ~/.ssh/id_landing_page
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          ssh-keyscan -H 34.128.116.49 >> ~/.ssh/known_hosts

      - name: Upload build output to server
        run: |
          scp -v -i ~/.ssh/id_landing_page -o StrictHostKeyChecking=no -r \
            .next/standalone \
            .next/static \
            public \
            package.json \
            ppidev@34.128.116.49:~/apps/samtek.id/

      - name: Deploy on server via SSH
        run: |
          ssh -i ~/.ssh/id_landing_page -o StrictHostKeyChecking=no -t ppidev@34.128.116.49 << 'EOF'
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            source ~/.bashrc
            nvm use 22.15.0

            cd ~/apps/samtek.id

            # Install pm2 jika belum ada
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi

            # Restart atau jalankan server Next.js menggunakan PM2
            PORT=3000
            if pm2 list | grep -q 'samtek'; then
              pm2 restart samtek
            else
              pm2 start standalone/server.js --name "samtek" -- --port $PORT
            fi
          EOF
