name: Deploy to GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 34.34.218.54 >> ~/.ssh/known_hosts

      - name: Deploy to GCP
        run: |
          ssh -i ~/.ssh/id_ed25519 ppidev@34.34.218.54 << 'EOF'
            cd ~/apps/samtek.id  # ubah sesuai subdomain kalau perlu
            git pull origin main || git clone git@github.com:PPI-DEV-ORG/dashboard-samtek.git .
            npm install --legacy-peer-deps
            npm run build
            pm2 restart samtek || pm2 start 'npm start' --name samtek --port 3000
          EOF
