name: Deploy to GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SECRET_SAMTEK_LANDING }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          ssh-keyscan -H 34.34.218.54 >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      - name: Deploy to GCP
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ServerAliveCountMax=5 -t ppidev@34.34.218.54 << 'EOF'
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            source ~/.bashrc
            nvm use 22.15.0
            cd ~/apps/samtek.id  # ubah sesuai subdomain kalau perlu

            # Cek apakah direktori adalah repo git atau tidak
            if [ -d .git ]; then
              # Jika sudah repo git, lakukan git pull
              git pull origin main
            else
              # Jika belum repo git, clone repository
              git clone git@github.com:PPI-DEV-ORG/samtek-landing-page.git .
            fi

            npm install --legacy-peer-deps

            PORT=3000
            # Cek apakah proses sudah ada, restart jika ada, atau start baru
            if pm2 list | grep -q 'samtek'; then
              pm2 restart samtek
            else
              pm2 list | grep -q "samtek" && pm2 restart samtek --port $PORT || pm2 start npm --name "samtek" -- run start -- --port $PORT
            fi
          EOF
